- size: small
  type: claim
  frozen: false
  split: cluster
  model_id: sentence-transformers/LaBSE
  train_loss: 0.365
  train_factual_f1: 0.455
  train_misinfo_f1: 0.946
  val_loss: 0.433
  val_factual_f1: 0.150
  val_misinfo_f1: 0.925
  test_loss: 0.396
  test_factual_f1: 0.303
  test_misinfo_f1: 0.948

- size: small
  type: claim
  frozen: true
  split: cluster
  model_id: sentence-transformers/LaBSE
  train_loss: 0.459
  train_factual_f1: 0.374
  train_misinfo_f1: 0.917
  val_loss: 0.513
  val_factual_f1: 0.157
  val_misinfo_f1: 0.903
  test_loss: 0.511
  test_factual_f1: 0.216
  test_misinfo_f1: 0.934

- size: medium
  type: claim
  frozen: false
  split: cluster
  model_id: sentence-transformers/LaBSE
  train_loss: 0.183
  train_factual_f1: 0.608
  train_misinfo_f1: 0.965
  val_loss: 0.327
  val_factual_f1: 0.290
  val_misinfo_f1: 0.964
  test_loss: 0.515
  test_factual_f1: 0.195
  test_misinfo_f1: 0.922

- size: medium
  type: claim
  frozen: true
  split: random
  model_id: sentence-transformers/LaBSE
  train_loss: 0.425
  train_factual_f1: 0.333
  train_misinfo_f1: 0.942
  val_loss: 0.342
  val_factual_f1: 0.237
  val_misinfo_f1: 0.952
  test_loss: 0.507
  test_factual_f1: 0.173
  test_misinfo_f1: 0.909

- size: large
  type: claim
  frozen: false
  split: cluster
  model_id: sentence-transformers/LaBSE
  train_loss: 0.183
  train_factual_f1: 0.529
  train_misinfo_f1: 0.968
  val_loss: 0.220
  val_factual_f1: 0.299
  val_misinfo_f1: 0.974
  test_loss: 0.317
  test_factual_f1: 0.217
  test_misinfo_f1: 0.041

- size: large
  type: claim
  frozen: true
  split: random
  model_id: sentence-transformers/LaBSE
  train_loss: 0.400
  train_factual_f1: 0.300
  train_misinfo_f1: 0.950
  val_loss: 0.309
  val_factual_f1: 0.262
  val_misinfo_f1: 0.966
  test_loss: 0.378
  test_factual_f1: 0.160
  test_misinfo_f1: 0.940

- size: small
  type: source-tweet
  frozen: false
  split: cluster
  model_id: sentence-transformers/LaBSE
  train_loss: 0.030
  train_factual_f1: 0.984
  train_misinfo_f1: 0.999
  val_loss: 1.281
  val_factual_f1: 0.040
  val_misinfo_f1: 0.927
  test_loss: 1.227
  test_factual_f1: 0.152
  test_misinfo_f1: 0.938

- size: medium
  type: source-tweet
  frozen: false
  split: cluster
  model_id: sentence-transformers/LaBSE
  train_loss: 0.006
  train_factual_f1: 0.996
  train_misinfo_f1: 1.000
  val_loss: 2.146
  val_factual_f1: 0.164
  val_misinfo_f1: 0.959
  test_loss: 3.040
  test_factual_f1: 0.207
  test_misinfo_f1: 0.942

- size: large
  type: source-tweet
  frozen: false
  split: cluster
  model_id: sentence-transformers/LaBSE
  train_loss: 0.825
  train_factual_f1: 0.142
  train_misinfo_f1: 0.975
  val_loss: 0.391
  val_factual_f1: 0.071
  val_misinfo_f1: 0.989
  test_loss: 0.415
  test_factual_f1: 0.078
  test_misinfo_f1: 0.978

- size: small
  type: image
  frozen: false
  split: cluster
  model_id: google/vit-base-patch16-224-in21k
  train_loss: 2.788
  train_factual_f1: 0.332
  train_misinfo_f1: 0.738
  val_loss: 3.905
  val_factual_f1: 0.026
  val_misinfo_f1: 0.686
  test_loss: 3.725
  test_factual_f1: 0.161
  test_misinfo_f1: 0.679

- size: medium
  type: image
  frozen: false
  split: cluster
  model_id: google/vit-base-patch16-224-in21k
  train_loss: 1.500
  train_factual_f1: 0.321
  train_misinfo_f1: 0.808
  val_loss: 2.484
  val_factual_f1: 0.017
  val_misinfo_f1: 0.850
  test_loss: 3.306
  test_factual_f1: 0.087
  test_misinfo_f1: 0.766

- size: large
  type: image
  frozen: false
  split: cluster
  model_id: google/vit-base-patch16-224-in21k
  train_loss: 1.417
  train_factual_f1: 0.225
  train_misinfo_f1: 0.819
  val_loss: 1.494
  val_factual_f1: 0.022
  val_misinfo_f1: 0.840
  test_loss: 2.428
  test_factual_f1: 0.092
  test_misinfo_f1: 0.784

- size: small
  type: graph
  split: cluster
  nhops: 2
  hetero_layer_norm: true
  hidden_dim: 1024
  batch_size: 1024
  input_dropout: 0.5
  dropout: 0.5
  lr: 3e-4
  epochs: 300
  pos_weight: 20
  train_loss: 0.874
  train_factual_f1: 0.354
  val_loss: 2.216
  val_factual_f1: 0.076
  val_misinfo_f1: 0.665
  test_loss: 2.207
  test_factual_f1: 0.182
  test_misinfo_f1: 0.747

- size: small
  type: graph
  split: random
  nhops: 2
  hetero_layer_norm: true
  hidden_dim: 1024
  batch_size: 1024
  input_dropout: 0.5
  dropout: 0.5
  lr: 3e-4
  epochs: 300
  pos_weight: 20
  train_loss: 0.815
  train_factual_f1: 0.342
  val_loss: 1.866
  val_factual_f1: 0.333
  val_misinfo_f1: 0.810
  test_loss: 2.073
  test_factual_f1: 0.090
  test_misinfo_f1: 0.767

- size: medium
  type: graph
  split: cluster
  nhops: 2
  hetero_layer_norm: true
  hidden_dim: 1024
  batch_size: 1024
  input_dropout: 0.5
  dropout: 0.5
  lr: 3e-4
  epochs: 300
  pos_weight: 20
  train_loss: 0.894
  train_factual_f1: 0.284
  val_loss: 0.862
  val_factual_f1: 0.163
  val_misinfo_f1: 0.850
  test_loss: 1.324
  test_factual_f1: 0.201
  test_misinfo_f1: 0.754

- size: medium
  type: graph
  split: random
  nhops: 2
  hetero_layer_norm: true
  hidden_dim: 1024
  batch_size: 1024
  input_dropout: 0.5
  dropout: 0.5
  lr: 3e-4
  epochs: 300
  pos_weight: 20
  train_loss: 0.856
  train_factual_f1: 0.274
  val_loss: 1.519
  val_factual_f1: 0.315
  val_misinfo_f1: 0.869
  test_loss: 0.905
  test_factual_f1: 0.253
  test_misinfo_f1: 0.846

- size: large
  type: graph
  split: cluster
  nhops: 2
  hetero_layer_norm: true
  hidden_dim: 1024
  batch_size: 1024
  input_dropout: 0.5
  dropout: 0.5
  lr: 3e-4
  epochs: 300
  pos_weight: 20
  train_loss:
  train_factual_f1:
  train_misinfo_f1:
  val_loss:
  val_factual_f1:
  val_misinfo_f1:
  test_loss:
  test_factual_f1:
  test_misinfo_f1:

- size: large
  type: graph
  split: random
  nhops: 2
  hetero_layer_norm: true
  hidden_dim: 1024
  batch_size: 1024
  input_dropout: 0.5
  dropout: 0.5
  lr: 3e-4
  epochs: 300
  pos_weight: 20
  train_loss: 0.802
  train_factual_f1: 0.300
  val_loss: 0.831
  val_factual_f1: 0.229
  val_misinfo_f1: 0.900
  test_loss: 0.894
  test_factual_f1: 0.254
  test_misinfo_f1: 0.824
